server:
    port: 8080

cors:
  originPatterns: http://localhost:4200,http://localhost:3000,http://localhost:8080

file:
  upload-dir: C:/Udemy/Aprenda Spring Swagger Docker Kubernetes e mais/workspace/file_temp

reports:
  path: "/templates/reports"

email:
  subject: "Default subject"
  message: "Default message"

security:
  jwt:
    token:
      secret-key: ${JWT_SECRET_KEY:53cr37}
      expire-length: ${JWT_EXPIRATION_TIME:3600000}

spring:
  application:
    name: spring-rest-api
  profiles:
    active: default
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_rest_api?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
      ddl-auto: none
    open-in-view: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
    protocol: smtp
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB # tamanho dos pedaços do multipart
      max-file-size: 10MB # tamanho do arquivo para upload
      max-request-size: 15MB # tamanho de download

logging:
  level:
    root: DEBUG
    #net.sf.jasperreports.engine.*: TRACE
    #com.github.andre10dias.spring_rest_api: DEBUG
    #org.springframework.security: DEBUG

springdoc:
  paths-to-match:
    - /api/**/v1/**
  swagger-ui:
    use-root-path: true

