name: Continuous Integration and Delivery with Github Actions

on:
  push:
    branches:
      - "main"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Login to Docker Hub
      uses: actions/checkout@v4
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

    - uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin' # See 'Supported distributions' for available options
        cache: maven
