name: Continuous Integration and Delivery with Github Actions

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build Application .jar
        working-directory: ./spring-rest-api
        run: mvn clean package

      - name: Docker Compose Build
        working-directory: ./
        run: docker compose build

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      # Configuração e login AWS/ECR ANTES do push
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: 'false'

      - name: Tag and Push Docker Image to Amazon Container Registry - ECR
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/spring-rest-api:latest ${{ secrets.IMAGE_REPO_URL }}:latest
          docker tag ${{ secrets.DOCKER_USERNAME }}/spring-rest-api:latest ${{ secrets.IMAGE_REPO_URL }}:${{ github.run_id }}
          docker push ${{ secrets.IMAGE_REPO_URL }}:latest
          docker push ${{ secrets.IMAGE_REPO_URL }}:${{ github.run_id }}

      - name: Push to Docker Hub
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/spring-rest-api:latest ${{ secrets.DOCKER_USERNAME }}/spring-rest-api:${{ github.run_id }}
          docker push ${{ secrets.DOCKER_USERNAME }}/spring-rest-api:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/spring-rest-api:${{ github.run_id }}
