name: Continuous Integration and Delivery with Github Actions

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build Application .jar
        working-directory: ./spring-rest-api
        run: mvn clean package

      - name: Docker Compose Build
        working-directory: ./
        run: docker compose build

      - name: Push to Docker Hub
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_ACCESS_TOKEN }}
          docker tag spring-rest-api:latest ${{ secrets.DOCKER_USERNAME }}/spring-rest-api:${{ github.run_id }}
          docker push ${{ secrets.DOCKER_USERNAME }}/spring-rest-api:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/spring-rest-api:${{ github.run_id }}
